### ISSUE TITLE
bad argument #1 to "tonumber" (value expected)

### ISSUE THREAD

**Issue by norbcodes** [wiremod/wire-cpu#6]
Hello, I got an issue when I tried to run this simple test code on the CPU
![image](https://github.com/wiremod/wire-cpu/assets/82652695/cb3e978b-f9b7-4531-8f3c-a2bc242c874c)

The error:
![image](https://github.com/wiremod/wire-cpu/assets/82652695/bc32036c-6732-4264-8261-3d7254cfcfb6)

I don't really know what's going on, as nobody mentioned an issue like this, so sorry if this is a stupid bug report 😅

**Comment by thegrb93** [comment]
I think that commit should fix it
