### ISSUE TITLE
Zapping a register variable by its variable name doesn't free the actual register

### ISSUE THREAD

**Issue by DerelictDrone** [wiremod/wire-cpu#9]
Compare examples.

No zapping
![image](https://github.com/wiremod/wire-cpu/assets/57756830/ea6a2c17-9391-444a-84f0-5b4711a9988c)
Zapping the registers
![image](https://github.com/wiremod/wire-cpu/assets/57756830/47f73c6b-e96b-42e9-bece-a9d407bd8664)
Zapping the registers by their variable name
![image](https://github.com/wiremod/wire-cpu/assets/57756830/5d35552b-7977-414c-a42f-373ccbb01ca5)

Rather than guessing which register to zap or having to calculate which register the register keyword will preserve for the variable, it would be nice to allow us to free a busy register by the variable name that's using it.

**Comment by bjcscat** [comment]
While it is possible to know exactly where the register will be zapped in the program you give, its not always possible to know where with control flow that cant be 100% known at compile time. This is why register in C is "best effort" not an actual guarantee like it is in HLZASM. This is mathematically impossible to totally implement.

**Comment by DerelictDrone** [comment]
Current implementation zaps registers immediately after the compiler reads "ZAP (REGISTER)", so adding a compiler error/warning for trying to reference a register variable any line after the "ZAP (VARIABLE)" is made should be acceptable for making users not attempt to use zap in branches
